presta_sitemap:
  defaults:
    priority: 1
    changefreq: daily
    lastmod: now
  route_annotation_listener: true
  items_by_set: 50000
  generator: presta_sitemap.generator_default
  dumper: presta_sitemap.dumper_default
