presta_sitemap:
  resource: "@PrestaSitemapBundle/Resources/config/routing.yml"

controllers:
  resource: '../../src/Controller/'
  type: annotation
  prefix: /{_locale}
  requirements:
    _locale: '%app_locales%'
  defaults:
    _locale: '%locale%'
redirects:
  resource: '../../src/Controller/RedirectController.php'
  type: annotation
  requirements:
    slug: '.{4,100}'
blogs:
  prefix: /{_locale}
  requirements:
    _locale: '%app_locales%'
  defaults:
    _locale: '%locale%'
  resource: '../../src/Controller/BlogController.php'
  type: annotation



